name: first_pipeline

on: push

jobs:
  first_test:
    runs-on: ubuntu-latest
    steps:
      - name: echo!
        run: echo "!"
      - name: clone
        uses: actions/checkout@v4
      - name: echo.
        run: ls -la
