name: first_pipeline

on: push

jobs:
  first_test:
    runs-on: ubuntu-latest
    steps:
      - name: echo!
        run: echo "!"
      - name: clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token:  ${{ secrets.GITHUB_TOKEN }}
      - name: echo.
        run: ls -la
      - name: test_script
        run: |
          cd tests
          chmod +x build.sh
          ./build.sh
      - name: revert
        if: failure()
        run: |
          git config --global user.email "mrbogdanello@gmail.com"
          git config --global user.name "PipeLine"
          git revert HEAD
          git push
##
